# Default values for template-node-typescript.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global: {}

name: mq-quarkus-app

replicaCount: 1
logLevel: "debug"

image:
  repository: replace
  tag: replace
  pullPolicy: IfNotPresent
  port: 8080

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

route:
  enabled: true

ingress:
  enabled: false
  appid:
    enabled: false
    # web or app - https://cloud.ibm.com/docs/services/appid?topic=appid-kube-auth
    requestType: web

#  host: hello
  namespaceInHost: true
  subdomain: containers.appdomain.cloud
  path: "/"

#  tlsSecretName: ""

jaegerConfigName: jaeger-config
jaegerSecretName: jaeger-access

vcsInfo:
  repoUrl: ""
  branch: ""

partOf: ""

connectsTo: ""

runtime: quarkus

configmap:
  CHANNEL: IBM.APP.SVRCONN
  QM: QUICKSTART
  QUEUE_NAME: IBM.DEMO.Q
  APP_NAME: MQ-QUARKUS-APP
  HOST: qm-dev-ibm-mq.dev.svc.cluster.local
  PORT: 1414

secret:
  PASSWORD: YXBw
  USER: bXFhcHA=
  
certs:
  volumeName: certs  
  certSecretName: mq-client-jks 
  certPasswordSecretName: mq-client-jks-password
  volumeMountPath: "/certs"
  trustStoreFileName: truststore.jks
  keyStoreFileName: keystore.jks
