apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}
data:
  CHANNEL: {{ .Values.configmap.CHANNEL }}
  QM: {{ .Values.configmap.QM }}
  QUEUE_NAME: {{ .Values.configmap.QUEUE_NAME }}
  APP_NAME: {{ .Values.configmap.APP_NAME }}
  HOST: {{ .Values.configmap.HOST }}
  PORT: {{ .Values.configmap.PORT | squote }}
  