apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.name }}
spec:
  encryptedData:
    PASSWORD: {{ .Values.secret.PASSWORD }}
    USER: {{ .Values.secret.USER }}
  template:
    metadata:
      name: {{ .Values.name }}
  